# This is a basic workflow to help you get started with Actions

name: calc-push

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
      
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: compile to execute code
        run: python -m py_compile calc.py > ${{runner.workspace}}/build/calc.exe
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Run a one-line script
        run: python calc.py

      - name: Run a multi-line script
        run: python calc.py
          echo Add other actions to build,
          echo test, and deploy your project.

      - name: Upload Artifact
        with:
          name: Calculator
          path: "${{runner.workspace}}/build/"

      # commit bytecode file
      - name: Commit files
        run: |
            git add calc.exe
            git commit -a -m 'Changes pushed by GitHub Actions' || true
            git push origin main